apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
type: Opaque
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:ulzhwf6ZxXdSwkQVsUBfMJrbRgxdCxGHHpVEsE6Q6YfOQK6aiggF3Ln+ohEp4f+ELzQiLFXy5fyKsbU3vCqSOyyqtdVbrXI0BFNUZJ05/42AYZ8ja4rSJ+nZpVMfV0ZvgQDluS/2V3HMPo3/V32w5r0f9/FsNGdCaslBoqQqh2YY9fJhBRCXvNyL3OPbzHAxfn0d6pOe4s8NES4UFNzG6OfoqADO7/IxueKG238fSKxSWnu1WPTVfg==,iv:j2aOqTlXGlGmTAKU8rUVllJ/pKNlgZ91poC4aV4n188=,tag:TkYZMhydSRufXdZ4ofvm7Q==,type:str]
  CLOUDFLARE_ACCOUNT_TAG: ENC[AES256_GCM,data:eJH1PNtFjA0dUODDWZ/XRq1uSNnRxTOYFejOs+Pa6sw=,iv:g8bmYaZ/+E3DZEdQ6dY3EMksrEwNC8Chy+GtKJSH7Y0=,tag:T3opVqEz4LttSm0LvYMPTg==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Ytf5zaXvh/4IYgPfiRk3V/HikyqUdK2kJYn2fAz8zM9t6DeE,iv:DQZAzRnM9ZSXWr2Zxn3ffiQgr/AzM2Wiqa3hK+fTD8A=,tag:gCKIZY2C9JNdfI0Uv1YwCQ==,type:str]
  CLOUDFLARE_TUNNEL_SECRET: ENC[AES256_GCM,data:WgS1802IZ+fzuqGeOWxrIrcTB60iM7VM3f18dXTcT5EWzh7XedLoHuKJRbB+q2U3,iv:v0anJTnDvYa7bmEh3IOfgLPyRFU/H2Z3GIcX8Q/Yvyo=,tag:m+10qVLhAkzdUW2kaP8u3Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZDZLNS9SeU0zNGM0ck91
        cTE3WEJraEdJbFNjNG1YRmlGYXY4Sy8wSUZjClUydCs1MExTcVA1N2NRT1FZS3Va
        TnMvOVpQcWxEVUhUbU5zblI5WU9uODQKLS0tIC9GVlZUQnlQWWxCcjRYWEpENGt0
        TGtDM2pWV0ZPVXovMGNUZUtKZER3ZGsKTp6iQi0rRjmHWkCY5fzlRb6Ru1saUnrm
        UuqDd9hJGFYPWeB5KZhrD9hNsqHh68iZ7nltnyuPZyDIME8Pgxmqyw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T10:45:59Z"
  mac: ENC[AES256_GCM,data:hPgX+RTBuCPbqRyR1ARhd80XvRc7xhLRUHXSgotLnhLEQTbnGqZpzQv3PNKkkT93bpuxiH3ZhjitpNA+SYyajfxnv5R8b1kRY+t0iVhsL3SO06MG/lO6C7v3hq4OggXWEmbuNNC8zf0+SnvY2fFMu9Sw1zIINV7nw/wo3oCkeXI=,iv:47jxglzHbN8yJEAaRMMCd71CdEPnXYG6Ar+CC1He8qM=,tag:KUeAxmG7XR6lZZJJRdJZ+Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
