apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forgejo-db-creds
  namespace: dev-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: forgejo-db-creds
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/forgejo-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/forgejo-static
        property: password
