---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../components/alerts
resources:
  - ./namespace.yaml
  - ./vars.sops.yaml
  # cni
  - ./cni/cilium/ks.yaml
  # dns
  - ./dns/coredns/ks.yaml
  # scheduling
  - ./scheduling/descheduler/ks.yaml
  - ./scheduling/metrics-server/ks.yaml
  # storage
  - ./storage/snapshot-controller/ks.yaml
  # - ./storage/csi-driver-nfs/ks.yaml
  # networking
  - ./networking/multus/ks.yaml
  # images
  - ./images/spegel/ks.yaml
  # config
  - ./config/reloader/ks.yaml
  # devices
  # - ./devices/intel-device-plugin-operator/ks.yaml
