apiVersion: v1
kind: Secret
metadata:
  name: flux-vars
type: Opaque
stringData:
  IP_LB_CIDR: ENC[AES256_GCM,data:SDunthwESu1TrVk=,iv:8opRXS7SZtSDot97/zKcuRtysxVtUBotGFRjFsX+9y8=,tag:C3zZFm98gZ1fdhcQaeaj7A==,type:str]
  CILIUM_DEVICE: ENC[AES256_GCM,data:Y+GddVXZ,iv:h1gKcmwkHxDML7R0A9029dwX1YPAuqfophPbrK/VRBc=,tag:+1yZKI6sfaRVH+/YnpdxlA==,type:str]
  IP_CLUSTER_VIP: ENC[AES256_GCM,data:E4JYEWeCUxj9,iv:adBtTH3URwo3uhtQMdOH/2WcrI5TB5mL1g9k6mwJ0/c=,tag:YOZ0bmPK0NbODQZwy1TStw==,type:str]
sops:
  age:
    - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TkMrMndCZFpUY080VU9W
        NEZBNzJCdHFzbUN5RWFqdXJCdzFzMnF5UkFJCmlJOTNLZTM3MXlqWW15ekRicUhO
        cTI3M3hMbDlDRnhIU2dTbVRObEFlNGsKLS0tIE56Nm9maUtpY3hXUFdoUGs3eWkz
        VFMydnN4L1lMVGRZbVM5MFBwcG9DS1EKrttl/uy4yBjZp9p/1P6/USEHZSZAwTQ0
        YE2E0UYB9L6kxUj1RGizFIs7Xex3ODe/rWLjMjLj9F51+KoAehPtWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-25T16:13:02Z"
  mac: ENC[AES256_GCM,data:mOhzHB9M0WVtbOAFkZt5FPzT1tSQIU6aXcsaSuUd5jcXrko3KpxxmU9GU/TUalZiHtPFivvdHEh3I8IGZkZjlCnC8DZVsFTYZ3ZsfiotumzlKyUsoU+lu2xtx+qAXjO16R4XBpkapqEFv3ACzf7Pdz7AvECh2QzT3qjltUegMbI=,iv:uXGtoUe7p2kLqIEE/5AewTZ8FYBdKzv2GMV5eJtGS0A=,tag:2oFcSlody03NxAaPV29aFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
