apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app openwrt
  namespace: &namespace kubevirt
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kubevirt
  path: ./kubernetes/apps/kubevirt/openwrt/app
  postBuild:
    substitute:
      OPENWRT_ROUTER_NODE: talos-0d4c1
      OPENWRT_WAN_LINK: enp5s0.100
      OPENWRT_LAN_LINK: enp5s0.200
      OPENWRT_LAN_IP: 192.168.10.1
      OPENWRT_LAN_NETMASK: 255.255.255.0
