---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: ps4-fpkgi-scripts
    files:
      - ps4-fpkgi-json.sh
generatorOptions:
  disableNameSuffixHash: true
