---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: home-assistant
spec:
  interval: 30s
  module: http_2xx
  prober:
    url: blackbox-exporter-lan.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - http://home-assistant.home-system.svc.cluster.local:8123/
  metricRelabelings:
    - action: replace
      replacement: blackbox-exporter-lan
      targetLabel: service
