---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-bucket-provision
  namespace: storage
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: provision
          image: quay.io/minio/mc:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          envFrom:
            - secretRef:
                name: minio-secret
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /tmp/.mc;
              export MC_CONFIG_DIR=/tmp/.mc;
              mc alias set myminio http://minio.storage.svc.cluster.local:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
              
              BUCKETS="pg-default tempo-bucket pg-enc pg-default-s3 meilisearch-volsync mosquitto-volsync pgadmin-volsync coder-volsync forgejo-volsync omniroute-volsync zot-volsync atuin-volsync blocky-volsync copyparty-volsync esphome-volsync frigate-volsync home-assistant-cache-volsync home-assistant-volsync immich-volsync jdownloader-volsync jellyfin-volsync prowlarr-volsync pyload-volsync qbittorrent-volsync rustdesk-volsync stalwart-stalwart-mail-volsync syncthing-volsync unifi-volsync zealot-volsync vault-volsync"
              
              for bucket in $BUCKETS; do
                mc mb myminio/$bucket || true
              done
      restartPolicy: OnFailure
