apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:iPIZMKR1NZgKCw==,iv:rNMMbg3peOX9/n68FGpc+UuBXU5s92kfbx7esL7Mxoo=,tag:HSldkWmEQ5Zz2jhR8/GW3g==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:Jt9JX3HW8+s5D3HV1xcu4rhXAC7iDg==,iv:pGV/e9UkU3HwQKX7VKfBB3jvaL3FYXjGcvO5aPwsOzU=,tag:utXeuZLmH4q/NNbBdfjzmA==,type:str]
sops:
  age:
    - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaFdENEVrYmY4UG8wZjVR
        V1dSbTg1dXR4ZEExZGZZWFY4YlZSbUFmUXdjCnFSbGtnRnRYOVVQdG1XOTROaWt5
        Vnp6eE4zWi9JZkg5L3FURmtsanR6ancKLS0tIG9DOWlFYitBM21XTTZBVUFPdE9H
        eE5ZaEFyc25QNHZ1ZWluRENQTHNmZHcKVrJEti+SLqnpcgpbyI4fouYuoLIC0qbw
        FMIz396Z30X8HP3S+KfVbIgx6OWLVFAcyk2wQJz5JgL74eBnAK+46g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-01T21:11:26Z"
  mac: ENC[AES256_GCM,data:iT8a39EljKsJ3kfs33wnIyFMQns3FUv1mjB0ynSKo+0MnueSpS1WymIOFk7nNVIOAyN+ucKTwZ8+b2SuI+Ep9DWBSkrybxsUk3LN3yhg4vjPocHEPxy0RsmnssilmLbDL3CBVNhIBndiRKM4/M7kiw+KfwChDjEb6vqLPGiqn64=,iv:pQ/8YLy/uHnHhhkjXaheAJsc8SJxXqlPsNR25A/kCOg=,tag:76CeLfJGdJO3reSX9VFlpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
