apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:nr3XL7NwMd+x0oGryOILwYus6UDEEyOX/Q==,iv:Nr/klOC3PXs+L6YgvJVTCJ6Wdb3X69vSGJVOy5eWufg=,tag:Ul+d/D2HLUdtGv/2/wlJMQ==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:UVguMsFvnPKnpt7PE6mcqQKc4b9E95JA3YfY295C3w==,iv:AssfVBCgrw26hDziEXwxvvcXdeMXocIZ/VfOQd34Ecg=,tag:Rp74fwJzJKJTWdjB1UNfJQ==,type:str]
sops:
  age:
    - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVEY1anNwOWFvZmtXY0dO
        Y3FrYjQzQlBTMFVwSTJlUXc5WDRZeXpyYXp3ClFhWmN4K3RFUXV0ZzNTRCtlL2dK
        MkVhbmUybzJuZStLVk5VTXo3VGV4U00KLS0tIDlmUEdMTTZXN3FyVEFDVENYcHBl
        c1BVME51OHlwWlJoS01semhneUxMUFEKU+ij8MLbSNOuOtJw7d71ZSkPK7jWDBj4
        KGLNJeDUxEqo/jVRaGpicNSLTyNQRavTl52q0busFVSB6zAQXYfDiw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-01T21:39:59Z"
  mac: ENC[AES256_GCM,data:pWIzra0qYvHaafM+L1EdsfpRJty+vRn0Uq0AE49vr8aT6iyNOcEQEkJSiA66oBWAYd//BN3Qvnk2jmh1BhMwj7bRjvb0X+p8huaqmulrLBCPwd2i4h4cKzpDoT6NhfXbrZRF3XhwPdgmjGEsIDcCL8yaZicdLXLKrLwuFx2m1GQ=,iv:edKNoNNZmFYYjshS8U58kULUoGVlXGzst6ypZK2fMvQ=,tag:rDfrGXWbNfPqzaphSY+Bfw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
