---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-vector
  # annotations:
  #   cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  imageName: ghcr.io/immich-app/postgres:16-vectorchord0.3.0-pgvectors0.3.0
  postgresUID: 999
  postgresGID: 999
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: restart
  storage:
    size: 5Gi
    storageClass: ceph-block
  walStorage:
    storageClass: ceph-block
    size: 5Gi
  superuserSecret:
    name: pg-default-superuser
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: immich
      owner: app
      secret:
        name: pg-default-app
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
    shared_preload_libraries:
      - "vchord.so"
  monitoring:
    enablePodMonitor: true
