---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copyparty-hdd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: piraeus-storage
  resources:
    requests:
      storage: 100Gi
