---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: provider-sql-creds
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: provider-sql-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        endpoint: "pg-default-rw.db.svc.cluster.local"
        port: "5432"
  data:
    - secretKey: username
      remoteRef:
        key: secret/pg_default
        property: USER
    - secretKey: password
      remoteRef:
        key: secret/pg_default
        property: PASSWORD
