# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
# apiVersion: cilium.io/v2
# kind: CiliumNetworkPolicy
# metadata:
#   name: &app vault
#   namespace: *app
# spec:
#   endpointSelector: {}
#   ingress:
#     # same namespace
#     - fromEndpoints:
#         - matchLabels:
#             io.kubernetes.pod.namespace: *app
#     # external Ceph cluster
#     # - fromCIDRSet:
#     #     - cidr: "${IP_PVE_CEPH_CIDR}"
#   egress:
#     # same namespace
#     - toEndpoints:
#         - matchLabels:
#             io.kubernetes.pod.namespace: *app
#     # external Ceph cluster
#     # - toCIDRSet:
#     #     - cidr: "${IP_PVE_CEPH_CIDR}"
#     # k8s apiserver
#     - toEntities:
#         - kube-apiserver
#     - toEntities:
#         - world            
#     - toEntities:
#         - host
#       toPorts:
#         - ports:
#             - port: "6443"
# ---