apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bank-vaults
  namespace: vault
spec:
  interval: 10m
  url: oci://ghcr.io/bank-vaults/helm-charts
  type: oci
  # ref:
  #   tag: v1.22.1
# ---
# apiVersion: source.toolkit.fluxcd.io/v1
# kind: HelmRepository
# metadata:
#   name: vault-secrets-webhook 
#   namespace: vault
# spec:
#   interval: 10m
#   url: oci://ghcr.io/bank-vaults/helm-charts/vault-secrets-webhook 
#   type: oci
#   # ref:
#   #   tag: v1.21.1
# ---