apiVersion: v1
kind: Secret
metadata:
  name: game-fetcher-pac-secret
  namespace: tekton-pipelines
type: Opaque
stringData:
  provider.token: ENC[AES256_GCM,data:63Bku+dC3CO74kqSAYmfhnxe+9bzx2h/1yISIvBtP6ib3nfx5M4mLA==,iv:8RrtXtTIrRn4dJq3WJ4GXHs1Zfw7inRAAFoz8arlXnQ=,tag:SdVujNMAkyEDP9QheTmoRg==,type:str]
  webhook.secret: ENC[AES256_GCM,data:E7C2yXYAKstuSkRaQVk9J8nz5Kel6w+tlrUHNJ19ilLxcjFGiUE/ag==,iv:f5ES4OA+80PtzNkBNMbG/KpUDrjnSavNoDogxTxWPDk=,tag:kv6Ji5oTCXWpZ6ANZTZ79g==,type:str]
sops:
  age:
    - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSVRQM1NITFM1ZVdUVzdY
        RFIxZUxPOEJJZ2FmVEl0cllxKy9lRXJySndZCmRLbHl1Y1FLckViNmY1dHlWNVFm
        VHhmaThHSzBpek12ZWsrcVZyWHNJM1EKLS0tIHRHTHUxbFBTblVXMkl0cklMNTdT
        cjU2Sm84QUZUUkRlV1labStYTUszQ1EK4MLhQGiSg/UhAL/jelmSYmZ0Wvs1ZJk5
        jJWby0Jys08R6xaCmD8qL/N46D8MzGp0z5PJWhzp3qp1mVDiDD5mQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-09T13:58:56Z"
  mac: ENC[AES256_GCM,data:y6mw3mR0serkjnLeDTwQXISRMSR0AuZxTfdz55u1EVgrVz0PputAvG3tJiMcmrCCEa6EXxSygL857J2F0MxgeZgT/KGKqlZ34sAjU1sRKt94VeN9/nGqO20oa7XRgeafRP6W5ab2Ho4st+BU7EzRPRoFNO/iKNA33PRpIXhLLzs=,iv:+LB5R0wzVTVPKlcHaBOuMUyHd60+dGKwQqoml4HB7Pg=,tag:7z8GwzE99gV5EYgGGLCr6Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
