---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    receiver: matrix
    repeatInterval: 12h
    routes:
      - receiver: blackhole
        matchers:
          - name: alertname
            value: InfoInhibitor
            matchType: =
    groupBy:
      - alertname
      - cluster
      - job
    groupInterval: 5m
    groupWait: 1m

  inhibitRules:
    - equal:
        - alertname
        - namespace
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
      targetMatch:
        - name: severity
          value: warning
          matchType: =

  receivers:
    - name: blackhole
    - name: matrix
      webhookConfigs:
        - url: http://matrix-alertmanager.observability.svc.cluster.local:3000/alerts?secret=InternalMatrixToken123
