apiVersion: v1
kind: Secret
metadata:
    name: flux-vars
type: Opaque
stringData:
    #ENC[AES256_GCM,data:UGCRAhJbUNBUv5b39fzE5woQkAoqPd/SDOJboy6nsR/7,iv:mFQYS8SkskrQ6Z9AoFUPit6fTDCQePvmRETz+wqCnCM=,tag:ft4CG4JjaapbX3DV/7sbAA==,type:comment]
    #ENC[AES256_GCM,data:gRkBohl8ppPZFlDeGT6bDnF0xQId1q9ONft1e0L7rDRB,iv:21UzhYI6fhlgzLQX1c4+9fL0TxDNgCh73f9hPcGNF/o=,tag:QFZmSjk7xuM32sL+dsiEHA==,type:comment]
    PG_S3_FOLDER_PREV: ENC[AES256_GCM,data:nQXyFWR4fmMsCjM0Mg==,iv:JFl/QsKXomLqkHHKDTeMf8R4dNqLMLE4W9AUK64FMAc=,tag:jsJIrhf4MkDFJf991f4RrQ==,type:str]
    PG_S3_FOLDER_CURR: ENC[AES256_GCM,data:A3ogwUBT0Be9iMH/cg==,iv:GPJPyYZFExGRkIhf7gQKc+NWywsBsoIwImzAOxUij2Y=,tag:cNbSAbvARP256KWf4dyDrg==,type:str]
    VEC_PG_S3_FOLDER_PREV: ENC[AES256_GCM,data:yLDc9leIlvbv,iv:K6Mzk9XHm7RLgRD9KTnXuyyiL+J+rVVHyL323jz8/aM=,tag:PEOigtT30btjNt0myuPs7A==,type:str]
    VEC_PG_S3_FOLDER_CURR: ENC[AES256_GCM,data:BGmxVGpwMBb7ZbWdjg==,iv:YB4uglmFa0pEOtR5qRzISVc/s4RVY/mWGqiFPGXr60c=,tag:vjaZ9tL82bDWcXqygf1c0Q==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:RV1yJx99quBxDYUWGj3pT5gLv7RYNIARi8knUaaukaqudP3VpsQ=,iv:SKcQcxv4cNHelzxx4/ZfBLrAIAdptk0WSqPyfUldr9s=,tag:nCFGOeKrTfq99Vyjd9qK1Q==,type:str]
    #ENC[AES256_GCM,data:HM5qgNck3Py0431MQVANn1m3+t3B2dPSVhcsq/MPk3G7L3TWsaGU4046M1KloOt5GNp3KMwH01fd7Iu287RJv4Snaio=,iv:kEbcsSleCYrZN9T7bV2vVssbuISkaWe/pSGkM3btebU=,tag:afCvwA5ei2fBsQNDJ6ZVKQ==,type:comment]
sops:
    age:
        - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTUVPa1JIOWNrNjJrc2h4
            L0hVZENwSHNHanhEelRBNGFEVzFKbXhjZ0djCmRDcUxDd29KYjlCWWpGTFQ5Qjlq
            SFdiTVkydHVZMTVxZEpNNlVQUDExUEkKLS0tIDcwYXVtWlRZQnZoMkIrWGszd0pO
            YzNXZkR0cTJDM3p5Z3lTRUliNkZqQ1EK8QEWCwKmKUlx+RtH0ouUVbcBTrxuq9FC
            wbUg8kv6lQ/HgFHaJI0Tux+jXUQgo/U+d9TVtaMyZ4GMAEnqGP/suw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T18:58:17Z"
    mac: ENC[AES256_GCM,data:udU32ZzVEnn4dUGazUzxUZ0ERFolthpCGe18BZl1AHe5H2BrcSh2bBrKwGHvR5MIswJgPu6fqqG83hym8puSvR3KTgggH7ODd/W0dSHcuNcg1R9uxOWcmXlr54+8RyeNwr2IjWfs+O1mmio0SU4l5FGqfmCIzm+9ycQiNfLuOPU=,iv:jKd8yRxMPXOB8lBItkVNWTSvrUcVOU0WX1Yr8AVVG5Y=,tag:oOpWihclO3unGihhxhen9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
