apiVersion: v1
kind: Secret
metadata:
    name: flux-vars
type: Opaque
stringData:
    PG_S3_FOLDER_PREV: ENC[AES256_GCM,data:k0YMy/GppPNQzP3vwA==,iv:32/75Cw0LNpnrN4qJ30IjDxTPd4GxjsOu+K9JTdDTH4=,tag:gv3ATzz2Vwxg9htn1L6DpQ==,type:str]
    PG_S3_FOLDER_CURR: ENC[AES256_GCM,data:CvBm1Nc2K0n6YH39Mw==,iv:/AA8/p3RHerlt0GkpB6wBQ33bP45Bi9WKfthuYCEi1A=,tag:DS72xi6GCxPWFmM1nZ3c0g==,type:str]
    VEC_PG_S3_FOLDER_PREV: ENC[AES256_GCM,data:yLDc9leIlvbv,iv:K6Mzk9XHm7RLgRD9KTnXuyyiL+J+rVVHyL323jz8/aM=,tag:PEOigtT30btjNt0myuPs7A==,type:str]
    VEC_PG_S3_FOLDER_CURR: ENC[AES256_GCM,data:BGmxVGpwMBb7ZbWdjg==,iv:YB4uglmFa0pEOtR5qRzISVc/s4RVY/mWGqiFPGXr60c=,tag:vjaZ9tL82bDWcXqygf1c0Q==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:RV1yJx99quBxDYUWGj3pT5gLv7RYNIARi8knUaaukaqudP3VpsQ=,iv:SKcQcxv4cNHelzxx4/ZfBLrAIAdptk0WSqPyfUldr9s=,tag:nCFGOeKrTfq99Vyjd9qK1Q==,type:str]
    #ENC[AES256_GCM,data:HM5qgNck3Py0431MQVANn1m3+t3B2dPSVhcsq/MPk3G7L3TWsaGU4046M1KloOt5GNp3KMwH01fd7Iu287RJv4Snaio=,iv:kEbcsSleCYrZN9T7bV2vVssbuISkaWe/pSGkM3btebU=,tag:afCvwA5ei2fBsQNDJ6ZVKQ==,type:comment]
sops:
    age:
        - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTUVPa1JIOWNrNjJrc2h4
            L0hVZENwSHNHanhEelRBNGFEVzFKbXhjZ0djCmRDcUxDd29KYjlCWWpGTFQ5Qjlq
            SFdiTVkydHVZMTVxZEpNNlVQUDExUEkKLS0tIDcwYXVtWlRZQnZoMkIrWGszd0pO
            YzNXZkR0cTJDM3p5Z3lTRUliNkZqQ1EK8QEWCwKmKUlx+RtH0ouUVbcBTrxuq9FC
            wbUg8kv6lQ/HgFHaJI0Tux+jXUQgo/U+d9TVtaMyZ4GMAEnqGP/suw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T14:35:38Z"
    mac: ENC[AES256_GCM,data:sUsA9VggwQRhX4ZVHMn5hzLJ5TEilsNnBYNs2lVJqSggwLLIjRQa+UzGdDaa8e8C5ofvODDym+XDrNs99mCiS6BMZObg1pz+lf4MTzXrvF7NJeWYXkPvYkV+oawj8QHxglW0IwunHIkBOr/yt0INaAJbfpUb2fO6QcfWdc9cMRQ=,iv:rzlmClOEGafarvDwPNwOW0JmBzKucUKRsxJgHYPe3pw=,tag:lqZrYBc11/BNnaV11Z8qRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
