---
spegel:
  containerdSock: ""
  containerdRegistryConfigPath: /etc/cri/conf.d/hosts
  containerdMirrorAdd: false
service:
  registry:
    hostPort: 29999
serviceMonitor:
  enabled: true
grafanaDashboard:
  enabled: true
