---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-vector
  # annotations:
  #   cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16-v0.3.0
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: restart
  storage:
    size: 5Gi
    storageClass: ceph-block
  walStorage:
    storageClass: ceph-block
    size: 5Gi
  superuserSecret:
    name: pg-default-superuser
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: immich
      owner: app
      secret:
        name: pg-default-app
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
    shared_preload_libraries:
      - "vectors.so"
  monitoring:
    enablePodMonitor: true
