apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synapse-db-creds
  namespace: db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: synapse-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/synapse-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/synapse-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mas-db-creds
  namespace: db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: mas-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/mas-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/mas-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atuin-db-creds
  namespace: db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: atuin-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/atuin-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/atuin-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-db-creds
  namespace: db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: vaultwarden-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/vaultwarden-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/vaultwarden-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zealot-db-creds
  namespace: db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: zealot-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/zealot-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/zealot-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zitadel-db-creds
  namespace: db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: zitadel-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/zitadel-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/zitadel-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forgejo-db-creds
  namespace: db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: forgejo-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/forgejo-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/forgejo-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-db-creds
  namespace: db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: coder-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/coder-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/coder-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: litellm-db-creds
  namespace: db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: litellm-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/litellm-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/litellm-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keto-db-creds
  namespace: db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: keto-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/keto-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/keto-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: temporal-db-creds
  namespace: db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: temporal-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/temporal-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/temporal-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: game-fetcher-db-creds
  namespace: db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: game-fetcher-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/game-fetcher-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/game-fetcher-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: settings-server-db-creds
  namespace: db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: settings-server-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/settings-server-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/settings-server-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mautrix-discord-db-creds
  namespace: db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: mautrix-discord-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/mautrix-discord-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/mautrix-discord-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mautrix-whatsapp-db-creds
  namespace: db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: mautrix-whatsapp-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/mautrix-whatsapp-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/mautrix-whatsapp-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mautrix-telegram-db-creds
  namespace: db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: mautrix-telegram-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/mautrix-telegram-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/mautrix-telegram-static
        property: password
