apiVersion: v1
kind: Secret
metadata:
  name: pg-default-offsite
  namespace: db
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:A4iVhgtUmJxli17f3EZHSA1i8mtPm5IOxQ==,iv:B1gmaDC8f3CBl0WrLODrD6X6sXLLWNXVw/8WTzwFRa8=,tag:UGUHlILgc4+7VhaqfdKriA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:SBrEu0NxcwqPeozEsZYFnGZlNNDK6NVJd9uXuUtQ7g==,iv:pbXA6TR8uE/3GQJDObk3v/XT07JeaNE82P40xvOfps4=,tag:KsYWfynUzt8RWb526UMrZA==,type:str]
sops:
  age:
    - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WXBRL2hNdU5aR0oxZk9R
        NnNXK05RWjdvM1NnMUp6N2JMWElVNVRRTmhvCnJhdy9wUnhEczYzMEZTbTg0M3Bo
        LzlBeWgxdHJPN2VpRmFYMlVxdlVuY1kKLS0tIFBaYTNyZDJUU00wUytnbFpnZGs2
        RXBVZUpsT1RoaElMSVluZ2FCWkxKN3cKagZypAV132VWYhwqmu1TAuqMNYLDFm/V
        OhJqHv5PCSbjPZne5MFYpw69GxXbHGEJwL9ZCs60MJ/dg9v1F6P3Og==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-29T21:44:16Z"
  mac: ENC[AES256_GCM,data:UbHLAM/uKlKdn3wr+UYkShoE6coiLuSRklTL+SshCDK2BJqe/LKBc4Pf8p5qB+6rMvfDodrugTh5zhY3otmhKdFW1YH1SjOpn6UlbSMWjG93y89HYsUdwEA+H0smd9ZDLGJHu52MobDKQLxy6qc27e3OVvQzcwYPv+0q9lMIy8g=,iv:3bIYUn8p4WL9c3w52Kmu/WuqymLenJtK/QUcpaJnJ7A=,tag:AE0Qa6qd8btZyawq1aYjqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
