apiVersion: v1
kind: Secret
metadata:
  name: pg-default-offsite
  namespace: db
  annotations:
    vault.security.banzaicloud.io/mutate: "true"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "vault:secret/data/cloudflare#AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "vault:secret/data/cloudflare#AWS_SECRET_ACCESS_KEY"
