---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ${APP}-volsync-values
    files:
      - values.yaml=volsync.values.yaml
  - name: pyload-scripts
    files:
      - delete_files.sh
