---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./helmrelease.yaml
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: ${APP}
      spec:
        dependsOn:
          - name: ${APP}-volsync
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: ${APP}
