---
apiVersion: v1
kind: Secret
metadata:
  name: volsync-offsite
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "vault:secret/data/backblaze#ID"
  AWS_SECRET_ACCESS_KEY: "vault:secret/data/backblaze#SECRET"
  KOPIA_PASSWORD: "vault:secret/data/volsync#KOPIA_PASSWORD"
