# Homeserver details.
homeserver:
  # The address that this appservice can use to connect to the homeserver.
  address: http://matrix-synapse:8008
  # The domain of the homeserver (also known as server_name, used for MXIDs, etc).
  domain: "${DOMAIN1}"

  # What software is the homeserver running?
  # Standard Matrix homeservers like Synapse, Dendrite and Conduit should just use "standard" here.
  software: standard
  # The URL to push real-time bridge status to.
  status_endpoint: null
  # Endpoint for reporting per-message status.
  message_send_checkpoint_endpoint: null
  # Does the homeserver support https://github.com/matrix-org/matrix-spec-proposals/pull/2246?
  async_media: false

  # Should the bridge use a websocket for connecting to the homeserver?
  websocket: false
  # How often should the websocket be pinged? Pinging will be disabled if this is zero.
  ping_interval_seconds: 0

# Application service host/registration related details.
# Changing these values requires regeneration of the registration.
appservice:
  # The address that the homeserver can use to connect to this appservice.
  address: http://mautrix-discord:8000

  # The hostname and port where this appservice should listen.
  hostname: 0.0.0.0
  port: 8000

  # Database config.
  database:
    # The database type. "sqlite3-fk-wal" and "postgres" are supported.
    type: postgres
    # The database URI.
    uri: "postgres://$${vault:secret/data/pg_default#USER}:$${vault:secret/data/pg_default#PASSWORD}@$${vault:secret/data/pg_default#HOST}:5432/mautrix-discord"
    # Maximum number of connections. Mostly relevant for Postgres.
    max_open_conns: 20
    max_idle_conns: 2
    # Maximum connection idle time and lifetime before they're closed. Disabled if null.
    max_conn_idle_time: null
    max_conn_lifetime: null

  # The unique ID of this appservice.
  id: discord
  # Appservice bot details.
  bot:
    # Username of the appservice bot.
    username: discordbot
    # Display name and avatar for bot.
    displayname: Discord bridge bot
    avatar: mxc://maunium.net/nIdEykemnwdisvHbpxflpDlC

  # Whether or not to receive ephemeral events via appservice transactions.
  ephemeral_events: true

  # Should incoming events be handled asynchronously?
  async_transactions: false

  # Authentication tokens for AS <-> HS communication. Autogenerated; do not modify.
  as_token: $${vault:secret/data/mautrix#hs_token}
  hs_token: $${vault:secret/data/mautrix#hs_token}

# Bridge config
bridge:
  # Localpart template of MXIDs for Discord users.
  username_template: discord_{{.}}
  # Displayname template for Discord users.
  displayname_template: '{{if .Webhook}}Webhook{{else}}{{or .GlobalName .Username}}{{if .Bot}} (bot){{end}}{{end}}'
  # Displayname template for Discord channels (bridged as rooms, or spaces when type=4).
  channel_name_template: '{{if or (eq .Type 3) (eq .Type 4)}}{{.Name}}{{else}}#{{.Name}}{{end}}'
  # Displayname template for Discord guilds (bridged as spaces).
  guild_name_template: '{{.Name}}'
  # Whether to explicitly set the avatar and room name for private chat portal rooms.
  private_chat_portal_meta: default

  # Publicly accessible base URL that Discord can use to reach the bridge.
  public_address: null
  # A random key used to sign the avatar URLs.
  avatar_proxy_key: generate

  portal_message_buffer: 128

  # Number of private channel portals to create on bridge startup.
  startup_private_channel_create_limit: 5
  # Should the bridge send a read receipt from the bridge bot when a message has been sent to Discord?
  delivery_receipts: false
  # Whether the bridge should send the message status as a custom com.beeper.message_send_status event.
  message_status_events: false
  # Whether the bridge should send error notices via m.notice events when a message fails to bridge.
  message_error_notices: true
  # Should the bridge use space-restricted join rules instead of invite-only for guild rooms?
  restricted_rooms: false
  # Should the bridge automatically join the user to threads on Discord when the thread is opened on Matrix?
  autojoin_thread_on_open: true
  # Should inline fields in Discord embeds be bridged as HTML tables to Matrix?
  embed_fields_as_tables: true
  # Should guild channels be muted when the portal is created?
  mute_channels_on_create: false
  # Should the bridge update the m.direct account data event when double puppeting is enabled.
  sync_direct_chat_list: false
  # Set this to true to tell the bridge to re-send m.bridge events to all rooms on the next run.
  resend_bridge_info: false
  # Should incoming custom emoji reactions be bridged as mxc:// URIs?
  custom_emoji_reactions: true
  # Should the bridge attempt to completely delete portal rooms when a channel is deleted on Discord?
  delete_portal_on_channel_delete: false
  # Should the bridge delete all portal rooms when you leave a guild on Discord?
  delete_guild_on_leave: true
  # Whether or not created rooms should have federation enabled.
  federate_rooms: true
  # Prefix messages from webhooks with the profile info?
  prefix_webhook_messages: true
  # Bridge webhook avatars?
  enable_webhook_avatars: false
  # Should the bridge upload media to the Discord CDN directly before sending the message.
  use_discord_cdn_upload: true
  # Should the bridge forbid direct messages from users to other users who they aren't friends with?
  forbid_dming_strangers: true
  # Proxy for Discord connections
  proxy:
  # Should mxc uris copied from Discord be cached?
  cache_media: unencrypted
  # Settings for converting Discord media to custom mxc:// URIs instead of reuploading.
  direct_media:
    # Should custom mxc:// URIs be used instead of reuploading media?
    enabled: false
    # The server name to use for the custom mxc:// URIs.
    server_name: discord-media.example.com
    # Optionally a custom .well-known response.
    well_known_response:
    # Allow proxying media if redirects are not supported.
    allow_proxy: true
    # Matrix server signing key.
    server_key: generate
  # Settings for converting animated stickers.
  animated_sticker:
    target: webp
    # Arguments for converter.
    args:
      width: 320
      height: 320
      fps: 25
  # Servers to always allow double puppeting from
  double_puppet_server_map:
    ${DOMAIN1}: https://${DOMAIN1}
  # Allow using double puppeting from any server with a valid client .well-known file.
  double_puppet_allow_discovery: false
  # Shared secrets for automatic double puppeting.
  login_shared_secret_map:
    ${DOMAIN1}: as_token:$${vault:secret/data/mautrix#hs_token}

  # The prefix for commands.
  command_prefix: '!discord'
  # Messages sent upon joining a management room.
  management_room_text:
    welcome: "Hello, I'm a Discord bridge bot."
    welcome_connected: "Use `help` for help."
    welcome_unconnected: "Use `help` for help or `login` to log in."
    additional_help: ""

  # Settings for backfilling messages.
  backfill:
    # Limits for forward backfilling.
    forward_limits:
      initial:
        dm: 0
        channel: 0
        thread: 0
      missed:
        dm: 0
        channel: 0
        thread: 0
    # Maximum members in a guild to enable backfilling.
    max_guild_members: -1

  # End-to-bridge encryption support options.
  encryption:
    # Allow encryption, work in group chat rooms with e2ee enabled
    allow: false
    # Default to encryption
    default: false
    # Whether to use MSC2409/MSC3202 instead of /sync long polling.
    appservice: false
    # Whether to use MSC4190 instead of appservice login.
    msc4190: false
    # Require encryption, drop any unencrypted messages.
    require: false
    # Enable key sharing?
    allow_key_sharing: false
    # Should users mentions be in the event wire content?
    plaintext_mentions: false
    # Options for deleting megolm sessions from the bridge.
    delete_keys:
      delete_outbound_on_ack: false
      dont_store_outbound: false
      ratchet_on_decrypt: false
      delete_fully_used_on_decrypt: false
      delete_prev_on_new_session: false
      delete_on_device_delete: false
      periodically_delete_expired: false
      delete_outdated_inbound: false
    # What level of device verification should be required?
    verification_levels:
      receive: unverified
      send: unverified
      share: cross-signed-tofu
    # Options for Megolm room key rotation.
    rotation:
      enable_custom: false
      milliseconds: 604800000
      messages: 100
      disable_device_change_key_rotation: false

  # Settings for provisioning API
  provisioning:
    prefix: /_matrix/provision
    shared_secret: generate
    debug_endpoints: false

  # Permissions for using the bridge.
  permissions:
    "*": relay
    "${DOMAIN1}": user
    "@zitadel-admin:${DOMAIN1}": admin

# Logging config.
logging:
  min_level: info
  writers:
    - type: stdout
      format: pretty-colored