---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sms-vault
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  install:
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    disableWait: true
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      sms-vault:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            vault.security.banzaicloud.io/vault-env-daemon: "true"
        containers:
          app:
            image:
              repository: zot.${DOMAIN1}/sms-vault
              tag: 7aae7e2c801cba7ff5cd1d263a0c315f3dacde78
            env:
              PORT: "8081"
              DATABASE_URL: "postgres://$${vault:database/creds/sms-vault-role#username}:$${vault:database/creds/sms-vault-role#password}@pg-default-rw.db.svc.cluster.local:5432/smsvault?sslmode=disable"
              AUTH_SERVER_ADDR: "auth-server.prod-system:50051"
              BASE_URL: "https://sms-vault.${DOMAIN1}"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETUID
                  - SETGID
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: sms-vault
        ports:
          http:
            port: 3000
    route:
      app:
        hostnames:
          - "sms-vault.${DOMAIN1}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - port: 3000
                name: *app
