---
autoDirectNodeRoutes: true
# bandwidthManager:
#   enabled: true
#   bbr: true
# bpf:
#   # datapathMode: netkit
  # masquerade: false
  # masquerade: true
#   preallocateMaps: true
#   # tproxy: true
  # hostLegacyRouting: false
# bpfClockProbe: true
# bgpControlPlane:
#   enabled: true
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cni:
  exclusive: false
dashboards:
  enabled: true
devices: ens3
# enableIPv4BIGTCP: true
endpointRoutes:
 enabled: true
envoy:
  rollOutPods: true
  prometheus:
     serviceMonitor:
       enabled: true
  log:
    defaultLevel: "trace"
gatewayAPI:
  enabled: true
  enableAlpn: true
  xffNumTrustedHops: 1
  # hostNetwork:
  #   enabled: true
hubble:
  enabled: false
ipam:
 mode: kubernetes
ipv4NativeRoutingCIDR: 10.42.0.0/16
k8sServiceHost: 10.0.2.15
k8sServicePort: 6443
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
l2announcements:
  enabled: true
loadBalancer:
  algorithm: maglev
  mode: dsr
localRedirectPolicy: true
operator:
  dashboards:
    enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  replicas: 2
  rollOutPods: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
rollOutCiliumPods: true
routingMode: native
# tunnelProtocol: "geneve"
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - PERFMON
      - BPF
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
