apiVersion: home.arpa/v1alpha1
kind: AppVaultPolicy
metadata:
  name: mautrix-telegram-vault
  namespace: home-system
spec:
  serviceAccount: mautrix-telegram
  policy: |
    path "secret/data/mautrix" {
      capabilities = ["read"]
    }
    path "secret/data/tg" {
      capabilities = ["read"]
    }
