# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: rook-config-override
# data:
#   config: |
#     [global]
#     ms_connection_ready_timeout = 10
#     ms_connection_idle_timeout = 10
#     rados_mon_op_timeout = 10
#     rados_osd_op_timeout = 10
#     client_mount_timeout = 10
#     osd_crush_update_on_start = false

#     [osd]
#     bluestore_block_db_size = 0
#     bluestore_block_wal_size = 0