apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keto-db-creds
  namespace: keto
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: keto-db-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DSN: "postgres://{{ .username }}:{{ .password }}@pg-default-rw.db.svc.cluster.local:5432/keto?sslmode=disable"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/keto-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/keto-static
        property: password
