---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keto
  labels:
    security.banzaicloud.io/mutate: skip
spec:
  interval: 1h
  chart:
    spec:
      chart: keto
      version: 0.62.1
      sourceRef:
        kind: HelmRepository
        name: ory
        namespace: keto
  values:
    keto:
      automigration:
        enabled: true
        type: initContainer
      config:
        dsn: "postgres://placeholder"
        namespaces:
          - id: 0
            name: sample
          - id: 1
            name: media_library
    deployment:
      automigration:
        extraEnv:
          - name: DSN
            valueFrom:
              secretKeyRef:
                name: keto-db-creds
                key: DSN
      podMetadata:
        annotations:
          vault.security.banzaicloud.io/vault-role: "default"
      extraEnv:
        - name: DSN
          valueFrom:
            secretKeyRef:
              name: keto-db-creds
              key: DSN
