---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keto
spec:
  interval: 1h
  chart:
    spec:
      chart: keto
      version: 0.62.1
      sourceRef:
        kind: HelmRepository
        name: ory
        namespace: keto
  values:
    keto:
      automigration:
        enabled: true
        type: initContainer
      config:
        dsn: "postgres://placeholder"
        namespaces:
          - id: 0
            name: sample
          - id: 1
            name: media_library
    deployment:
      automigration:
        extraEnv:
          - name: DSN
            value: "postgres://$${vault:database/creds/keto-role#username}:$${vault:database/creds/keto-role#password}@pg-default-rw.db.svc.cluster.local:5432/keto?sslmode=disable"
      podMetadata:
        annotations:
          vault.security.banzaicloud.io/vault-role: "default"
          vault.security.banzaicloud.io/vault-env-daemon: "true"
      extraEnv:
        - name: DSN
          value: "postgres://$${vault:database/creds/keto-role#username}:$${vault:database/creds/keto-role#password}@pg-default-rw.db.svc.cluster.local:5432/keto?sslmode=disable"
