---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing
  annotations:
    linstor.csi.linbit.com/placementCount: "1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linstor-ssd
  resources:
    requests:
      storage: 5Gi
