apiVersion: v1
kind: Secret
metadata:
  name: openwrt-secret
spec:
  stringData:
    OPENWRT_PPPOE_USER: vault:secret/data/wan:username
    OPENWRT_PPPOE_PASS: vault:secret/data/wan:password
    OPENWRT_LAN_IP: 10.0.0.6
    OPENWRT_LAN_NETMASK: 255.255.255.0
