apiVersion: v1
kind: Secret
metadata:
    name: pg-vault-superuser
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:3BAotP51JmQ=,iv:KxPPAnMJWXPnQ0Ya14OSLR1iSBqJ01lmDovfWZkPkYg=,tag:TGFIMRq3XLFiF5HQ+3AUEQ==,type:str]
    password: ENC[AES256_GCM,data:gg7cSFCyD1K068S07fE=,iv:hr2M/EKs823SU+4dRw5V8w0Lrjkeyl/saTXVVvq0/bo=,tag:j5Pzub+SIUap4zl6GG2sXQ==,type:str]
sops:
    age:
        - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHY3E0dUlBOUVqRjcyVGdR
            Mmw3OXRFTFRXdUNvNStUZlZ6cHNsd0I2c0RVCnFVZzlaY3pnU2E5dGpid0dXWW9t
            cGZjU2J2RGVLMW1ZS3BGQzVGdlhtY2cKLS0tIGh0VmFJbzl1empoRGJQNi9xUkdO
            dmQ4ODhYU1lRZVJUNmtFQkpHcDhhcnMKOAP70f3dIylATpTM4Z0un8mQl3ry/nrH
            cKMBLni8/pW0alTk3+yI+dXeMbOjQvO/WxRtEm38iyrHMkrXGL3+SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T06:37:05Z"
    mac: ENC[AES256_GCM,data:JfOoveRNqJXOUAaV+Bdj7YU1UB6wUiOA2Nj7UQcIfmb0UrP9i1jhGpIbkTxXodd2heIIqBkAWvorcPG8FWoQIL7nEBLCSmouha1tGYE52vXLVIqrN2FeNzdyZPjtKTHss4Y0sbuJ5aMPN/cFKx2nPAirigrD4qs0AXOd5/zH8iE=,iv:MzAw6Rwgs3cbrFSVIzdJReibqhDHalmjLuwk5sI48dM=,tag:OikONIfyUmONk7Fk7oUNrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
