---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: vault-db-static-roles
  namespace: vault
spec:
  interval: 1m
  retryInterval: 1m
  retryStrategy: StaticInterval
  approvePlan: auto  # Automatically apply changes
  path: ./terraform/vault
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  serviceAccountName: tf-runner
