---
apiVersion: v1
kind: Secret
metadata:
  name: nuviostreams-secret
type: Opaque
stringData:
  # TMDB_API_KEY: ""
  SHOWBOX_PROXY_URLS: ""
  FEBBOX_PROXY_URLS: ""
  VIDSRC_PROXY_URL: ""
  VIDZEE_PROXY_URL: ""
  SOAPERTV_PROXY_URL: ""
  UHDMOVIES_PROXY_URL: ""
  MOVIESMOD_PROXY_URL: ""
  TOPMOVIES_PROXY_URL: ""
  EXTERNAL_UHDMOVIES_URL: ""
  EXTERNAL_TOPMOVIES_URL: ""
  EXTERNAL_MOVIESMOD_URL: ""
  cookies.txt: ""
