apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-db-creds
  namespace: dev-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: coder-db-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        CODER_PG_CONNECTION_URL: "postgres://{{ .username }}:{{ .password }}@pg-default-rw.db.svc.cluster.local:5432/coder?sslmode=disable"
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/coder-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/coder-static
        property: password
