---
apiVersion: home.arpa/v1alpha1
kind: AppVaultPolicy
metadata:
  name: thumbnail-service-vault
  namespace: prod-system
spec:
  serviceAccount: default
  policy: |
    path "secret/data/cloudflare" {
      capabilities = ["read"]
    }
