---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app thumbnail-service
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  install:
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    disableWait: true
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      thumbnail-service:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            vault.security.banzaicloud.io/vault-env-daemon: "true"
        containers:
          app:
            image:
              repository: zot.${DOMAIN1}/thumbnail-service
              tag: 54db3db5514ba530ce5a760e1b469cf244dbc784
            env:
              PORT: &port "3000"
              GRPC_PORT: &grpcPort "50051"
              LOG_LEVEL: "INFO"
              ACCESS_KEY_ID: "vault:secret/data/cloudflare#AWS_ACCESS_KEY_ID"
              SECRET_ACCESS_KEY: "vault:secret/data/cloudflare#AWS_SECRET_ACCESS_KEY"
              ENDPOINT: "https://d4ecb65c48cd4a627c11099c8d9c9fb7.r2.cloudflarestorage.com"
              S3_PUBLIC_URL: "https://pub-d35100e1a2f040208680ad3f6e399d06.r2.dev"
              BUCKET: "thumbnails"
              URL: "dragonfly.db.svc.cluster.local:6379"
              TEMPORAL_HOST: "temporal.dev-system.svc.cluster.local:7233"
              TEMPORAL_NAMESPACE: "default"
              TEMPORAL_TASK_QUEUE: "thumbnail-tasks"
              CLEAN_ON_LAUNCH: "false"

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /metrics
                    port: 3000
                  initialDelaySeconds: 15
                  periodSeconds: 15
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /metrics
                    port: 3000
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /metrics
                    port: 3000
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 30
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
    service:

      app:
        controller: thumbnail-service
        ports:
          http:
            port: *port
          grpc:
            port: *grpcPort
