---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-xp-systemdisk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${STORE1}
  resources:
    requests:
      storage: 10Gi
