---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-xp-install-media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linstor-ssd
  resources:
    requests:
      storage: 2Gi
