---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - source.yaml
  - httproutes.yaml
  - netpol.yaml
  - secret.yaml
configMapGenerator:
  - name: mautrix-whatsapp-config
    options:
      annotations:
        vault.security.banzaicloud.io/mutate: "true"
    files:
      - ./whatsapp/config.yaml
      - ./whatsapp/registration.yaml
generatorOptions:
  disableNameSuffixHash: true
