---
apiVersion: v1
kind: Secret
metadata:
  name: matrix-postgres-creds
type: Opaque
stringData:
  password: vault:secret/data/pg_default#PASSWORD
  game-special-key: |
    password: $${vault:secret/data/pg_default#PASSWORD}
    domain1: ${DOMAIN1}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: matrix-postgres-configmap
data:
  domain: ${DOMAIN1}
  password: vault:secret/data/pg_default#PASSWORD
  game-special-key: |
    password: $${vault:secret/data/pg_default#PASSWORD}
    domain1: ${DOMAIN1}