---
apiVersion: v1
kind: Secret
metadata:
  name: matrix-postgres-creds
type: Opaque
stringData:
  password: vault:secret/data/pg_default#PASSWORD
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: matrix-postgres-configmap
data:
  password: vault:secret/data/pg_default#PASSWORD
  game-special-key: |
    password: ${vault:secret/data/pg_default#PASSWORD}