---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-system

configMapGenerator:
  - name: thumbnail-service-loadtest-script
    files:
      - test.js

generatorOptions:
  disableNameSuffixHash: true

resources:
  - testrun.yaml
