app: ""

defaults:
  schedule: "0 * * * *"
  accessModes:
    - ReadWriteOnce
  sourceAccessModes:
    - ReadWriteOnce
  cacheAccessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  cacheStorageClassName: ceph-block
  snapshotClassName: csi-ceph-blockpool
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  secretData:
    KOPIA_FS_PATH: /repository
    KOPIA_PASSWORD: vault:secret/data/volsync#RESTIC_PASSWORD
    KOPIA_S3_BUCKET: test
    KOPIA_REPOSITORY: s3:http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc:80/test
    KOPIA_S3_ENDPOINT: rook-ceph-rgw-ceph-objectstore.rook-ceph.svc:80
    AWS_S3_ENDPOINT: rook-ceph-rgw-ceph-objectstore.rook-ceph.svc:80
    AWS_ACCESS_KEY_ID: KNJOTGE7Q7BRRDHBCS4X
    AWS_SECRET_ACCESS_KEY: dG7hHBysokmVgkvIjCnl5L2pHwlc2cpoT4wen6Vb
    KOPIA_S3_DISABLE_TLS: "true"
    AWS_S3_DISABLE_TLS: "true"

volumes: []
