app: ""

defaults:
  schedule: "0 * * * *"
  accessModes:
    - ReadWriteOnce
  sourceAccessModes:
    - ReadWriteOnce
  cacheAccessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  cacheStorageClassName: ceph-block
  snapshotClassName: csi-ceph-blockpool
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  secretData: {}
  offsite:
    enabled: false
    schedule: ""
    repositorySecretName: volsync-offsite
    secretData: {}

volumes: []
