apiVersion: v1
kind: Secret
metadata:
    name: flux-vars
type: Opaque
stringData:
    #ENC[AES256_GCM,data:28MFeyc5Fmea1S004RHIDcyzdw0ZxglL31KCRHvCB6zX476KCNpXQvZZKHM=,iv:JMDQtOQuvZTusgFHZ5B6wQS8lMKXm+CdcHM5WZt0q2w=,tag:ZIow7q2REAfkcvmaGYl5EA==,type:comment]
    PG_S3_FOLDER_PREV: ENC[AES256_GCM,data:OgdOVJba5GVzObCmGQ==,iv:XpnBMmzxqVHWAT/GpBTPBgcEm8eKNRscJp9RI7GC9M4=,tag:/Cw2OPZqi9wgpxBg/fyuGg==,type:str]
    PG_S3_FOLDER_CURR: ENC[AES256_GCM,data:0H5wnAjBS57SK65Rug==,iv:3oGJKUKV5WHj83AuQ5IWx8bpgplnXH6clB0ixEWbZ5w=,tag:KfNjyCxFWzEIz0XwLhVbWQ==,type:str]
    VEC_PG_S3_FOLDER_PREV: ENC[AES256_GCM,data:yLDc9leIlvbv,iv:K6Mzk9XHm7RLgRD9KTnXuyyiL+J+rVVHyL323jz8/aM=,tag:PEOigtT30btjNt0myuPs7A==,type:str]
    VEC_PG_S3_FOLDER_CURR: ENC[AES256_GCM,data:BGmxVGpwMBb7ZbWdjg==,iv:YB4uglmFa0pEOtR5qRzISVc/s4RVY/mWGqiFPGXr60c=,tag:vjaZ9tL82bDWcXqygf1c0Q==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:RV1yJx99quBxDYUWGj3pT5gLv7RYNIARi8knUaaukaqudP3VpsQ=,iv:SKcQcxv4cNHelzxx4/ZfBLrAIAdptk0WSqPyfUldr9s=,tag:nCFGOeKrTfq99Vyjd9qK1Q==,type:str]
    #ENC[AES256_GCM,data:HM5qgNck3Py0431MQVANn1m3+t3B2dPSVhcsq/MPk3G7L3TWsaGU4046M1KloOt5GNp3KMwH01fd7Iu287RJv4Snaio=,iv:kEbcsSleCYrZN9T7bV2vVssbuISkaWe/pSGkM3btebU=,tag:afCvwA5ei2fBsQNDJ6ZVKQ==,type:comment]
sops:
    age:
        - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTUVPa1JIOWNrNjJrc2h4
            L0hVZENwSHNHanhEelRBNGFEVzFKbXhjZ0djCmRDcUxDd29KYjlCWWpGTFQ5Qjlq
            SFdiTVkydHVZMTVxZEpNNlVQUDExUEkKLS0tIDcwYXVtWlRZQnZoMkIrWGszd0pO
            YzNXZkR0cTJDM3p5Z3lTRUliNkZqQ1EK8QEWCwKmKUlx+RtH0ouUVbcBTrxuq9FC
            wbUg8kv6lQ/HgFHaJI0Tux+jXUQgo/U+d9TVtaMyZ4GMAEnqGP/suw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T13:23:54Z"
    mac: ENC[AES256_GCM,data:dcYwx6aP1WPnUlPGWHTWEsEjoUWYY3p23/xEN2JYL7YmxbGbp4yIqqPIcaKz1tFlGiUtLXwkGXQHbuEwobnH2frtDxnZivRqCR7NHP1Bl4Njs+/F5esOCq0iVD9qcgfZP5cji2ZYy3hMN+MlH2axvoXLJbOo5XUfn/DYBVL+Teo=,iv:MN/4858voca6McazjDrLVfqK0gTco/H8NbvlLu+J9zs=,tag:yWAkyKlzUdqj1fr51YSziw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
