---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  # metrics
  - ./metrics/kube-prometheus-stack/ks.yaml
  - ./metrics/vpa/ks.yaml
  - ./metrics/goldilocks/ks.yaml
  - ./metrics/keda/ks.yaml
  # logs
  - ./logs/fluent-bit/ks.yaml
  - ./logs/victoria-logs/ks.yaml
  # tracing
  - ./tracing/tempo/ks.yaml
  # collector
  - ./collector/opentelemetry/ks.yaml
  # dashboards
  - ./dashboards/grafana/ks.yaml
  - ./dashboards/kromgo/ks.yaml
  # exporters
  - ./exporters/blackbox-exporter/ks.yaml
  - ./exporters/smartctl-exporter/ks.yaml
  - ./exporters/snmp-exporter/ks.yaml
  # - ./exporters/unpoller/ks.yaml
  # alerting
  # - ./alerting/silence-operator/ks.yaml
  # uptime
  - ./uptime/gatus/ks.yaml
