apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synapse-db-creds
  namespace: home-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: synapse-db-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/synapse-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/synapse-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mas-db-creds
  namespace: home-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: mas-db-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/mas-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/mas-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: matrix-init-db-credentials
  namespace: home-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: matrix-init-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_PASS: "{{ .password }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .password }}"
        INIT_POSTGRES_SUPER_USER: "{{ .username }}"
        INIT_POSTGRES_USER: "{{ .username }}"
        SUPER_PASS: "{{ .password }}"
        SUPER_USER: "{{ .username }}"
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/pg_default
        property: data.USER
    - secretKey: password
      remoteRef:
        key: secret/data/pg_default
        property: data.PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mautrix-discord-db-creds
  namespace: home-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: mautrix-discord-db-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/mautrix-discord-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/mautrix-discord-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mautrix-whatsapp-db-creds
  namespace: home-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: mautrix-whatsapp-db-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/mautrix-whatsapp-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/mautrix-whatsapp-static
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mautrix-telegram-db-creds
  namespace: home-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: mautrix-telegram-db-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/mautrix-telegram-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/mautrix-telegram-static
        property: password

