kind: ExternalSecret
metadata:
  name: matrix-init-db-credentials
  namespace: home-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: matrix-init-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_PASS: "{{ .password }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .password }}"
        INIT_POSTGRES_SUPER_USER: "{{ .username }}"
        INIT_POSTGRES_USER: "{{ .username }}"
        SUPER_PASS: "{{ .password }}"
        SUPER_USER: "{{ .username }}"
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/pg_default
        property: data.USER
    - secretKey: password
      remoteRef:
        key: secret/data/pg_default
        property: data.PASSWORD
---
