---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - source.yaml
  - httproutes.yaml
  - netpol.yaml
  - secret.yaml
configMapGenerator:
  - name: mautrix-whatsapp-config
    files:
      - ./whatsapp/config.yaml
      - ./whatsapp/registration.yaml
      - ./whatsapp/doublepuppet.yaml
  - name: mautrix-telegram-config
    files:
      - ./telegram/config.yaml
      - ./telegram/registration.yaml
      - ./telegram/doublepuppet.yaml
  - name: mautrix-discord-config
    files:
      - ./discord/config.yaml
      - ./discord/registration.yaml
      - ./discord/doublepuppet.yaml
generatorOptions:
  disableNameSuffixHash: true
