apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-matrix-authentication-service
spec:
  template:
    spec:
      initContainers:
        - name: render-config
          envFrom:
            - secretRef:
                name: matrix-postgres-creds
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-synapse-main
spec:
  template:
    spec:
      initContainers:
        - name: render-config
          envFrom:
            - secretRef:
                name: matrix-postgres-creds
---
apiVersion: batch/v1
kind: Job
metadata:
  name: matrix-synapse-check-config
spec:
  template:
    spec:
      initContainers:
        - name: render-config
          envFrom:
            - secretRef:
                name: matrix-postgres-creds
