---
apiVersion: v1
kind: Secret
metadata:
  name: matrix-postgres-creds
type: Opaque
stringData:
  password: vault:database/creds/app-role#password
---
apiVersion: v1
kind: Secret
metadata:
  name: matrix-init-db-credentials
type: Opaque
stringData:
  INIT_POSTGRES_USER: "vault:database/creds/init-role#username"
  INIT_POSTGRES_PASS: "vault:database/creds/init-role#password"
  INIT_POSTGRES_SUPER_USER: "vault:database/creds/init-role#username"
  INIT_POSTGRES_SUPER_PASS: "vault:database/creds/init-role#password"
  SUPER_USER: "vault:database/creds/init-role#username"
  SUPER_PASS: "vault:database/creds/init-role#password"