---
apiVersion: v1
kind: Secret
metadata:
  name: immich-config
type: Opaque
stringData:
  immich-config.yaml: |
    oauth:
      enabled: true
      issuerUrl: https://zitadel.${DOMAIN1}
      clientId: ${client_id}
      clientSecret: ${client_secret}
      scope: openid email profile
      signingAlgorithm: RS256
      profileSigningAlgorithm: none
      tokenEndpointAuthMethod: client_secret_post
      buttonText: Login with Zitadel
      autoRegister: true
      autoLaunch: false
      mobileOverrideEnabled: true
      mobileRedirectUri: https://immich.${DOMAIN1}/api/oauth/mobile-redirect
      storageLabelClaim: preferred_username
    passwordLogin:
      enabled: true
    server:
      externalDomain: https://immich.${DOMAIN1}
