---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: email-fetcher
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.security.banzaicloud.io/vault-role: "default"
        spec:
          containers:
            - name: fetcher
              image: alpine:3.18
              command:
                - /bin/sh
                - /scripts/fetcher.sh
              volumeMounts:
                - name: scripts
                  mountPath: /scripts
              env:
                - name: AWS_ACCESS_KEY_ID
                  value: "vault:secret/data/cloudflare#AWS_ACCESS_KEY_ID"
                - name: AWS_SECRET_ACCESS_KEY
                  value: "vault:secret/data/cloudflare#AWS_SECRET_ACCESS_KEY"
                - name: R2_ACCOUNT_ID
                  value: "vault:secret/data/cloudflare#ACCOUNT_ID"
                - name: R2_BUCKET
                  value: "home-ops-email-inbox"
                - name: AWS_DEFAULT_REGION
                  value: "auto"
                - name: STALWART_URL
                  value: "http://stalwart-stalwart-mail.home-system.svc.cluster.local:80/.well-known/jmap"
                # Add this secret to Vault!
                - name: STALWART_TOKEN
                  value: "supersecret"
                - name: STALWART_ACCOUNT_ID
                  value: "admin"
          volumes:
            - name: scripts
              configMap:
                name: email-fetcher-script
                defaultMode: 0777
          restartPolicy: OnFailure
