---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tofu-email-routing.yaml
  - cronjob.yaml

configMapGenerator:
  - name: email-fetcher-script
    files:
      - fetcher.sh
generatorOptions:
  disableNameSuffixHash: true
