model_list:
  - model_name: "openai/gpt-5"
    litellm_params:
      model: "openai/gpt-5"
      api_key: your-api-key-here
      api_base: http://cliproxyapi:8317/v1

  - model_name: "openai/gpt-5-codex"
    litellm_params:
      model: "openai/gpt-5-codex"
      api_key: your-api-key-here
      api_base: http://cliproxyapi:8317/v1

  - model_name: "openai/gpt-5.1-codex-mini"
    litellm_params:
      model: "openai/gpt-5.1-codex-mini"
      api_key: your-api-key-here
      api_base: http://cliproxyapi:8317/v1

  - model_name: "openai/gpt-5.2"
    litellm_params:
      model: "openai/gpt-5.2"
      api_key: your-api-key-here
      api_base: http://cliproxyapi:8317/v1

  - model_name: "openai/gpt-5.4"
    litellm_params:
      model: "openai/gpt-5.4"
      api_key: your-api-key-here
      api_base: http://cliproxyapi:8317/v1

  - model_name: "openai/gpt-5-codex-mini"
    litellm_params:
      model: "openai/gpt-5-codex-mini"
      api_key: your-api-key-here
      api_base: http://cliproxyapi:8317/v1

  - model_name: "openai/gpt-5.2-codex"
    litellm_params:
      model: "openai/gpt-5.2-codex"
      api_key: your-api-key-here
      api_base: http://cliproxyapi:8317/v1

  - model_name: "openai/gpt-5.3-codex"
    litellm_params:
      model: "openai/gpt-5.3-codex"
      api_key: your-api-key-here
      api_base: http://cliproxyapi:8317/v1

  - model_name: "openai/gpt-5.1"
    litellm_params:
      model: "openai/gpt-5.1"
      api_key: your-api-key-here
      api_base: http://cliproxyapi:8317/v1

  - model_name: "openai/gpt-5.3-codex-spark"
    litellm_params:
      model: "openai/gpt-5.3-codex-spark"
      api_key: your-api-key-here
      api_base: http://cliproxyapi:8317/v1

  - model_name: "openai/gpt-5.1-codex"
    litellm_params:
      model: "openai/gpt-5.1-codex"
      api_key: your-api-key-here
      api_base: http://cliproxyapi:8317/v1

  - model_name: "openai/gpt-5.1-codex-max"
    litellm_params:
      model: "openai/gpt-5.1-codex-max"
      api_key: your-api-key-here
      api_base: http://cliproxyapi:8317/v1

  - model_name: "qwen/qwen3-coder-plus"
    litellm_params:
      model: "openai/qwen3-coder-plus"
      api_key: your-api-key-here
      api_base: http://cliproxyapi:8317/v1

  - model_name: "qwen/qwen3-coder-flash"
    litellm_params:
      model: "openai/qwen3-coder-flash"
      api_key: your-api-key-here
      api_base: http://cliproxyapi:8317/v1

  - model_name: "qwen/coder-model"
    litellm_params:
      model: "openai/coder-model"
      api_key: your-api-key-here
      api_base: http://cliproxyapi:8317/v1

  - model_name: "qwen/vision-model"
    litellm_params:
      model: "openai/vision-model"
      api_key: your-api-key-here
      api_base: http://cliproxyapi:8317/v1
  # - model_name: "antigravity/*"
  #   litellm_params:
  #     model: "antigravity/*"
  #     api_key: your-api-key-here
  #     custom_llm_provider: "openai"
  #     api_base: http://cliproxyapi:8317/v1
  # # Google
  # - model_name: gemini/*
  #   litellm_params:
  #     model: gemini/*
  #     api_key: os.environ/GOOGLE_API_KEY


litellm_settings:
  check_provider_endpoint: true
general_settings:
  allow_model_discovery: true
  master_key: os.environ/LITELLM_MASTER_KEY

mcp_servers:
  "flux_mcp":
    url: "http://flux-operator-mcp.flux-system.svc.cluster.local:9090/mcp"
  "ha_mcp":
    url: "http://home-assistant.home-system.svc.cluster.local:8086/mcp"
  "context7":
    url: "https://mcp.context7.com/mcp"
    headers:
      CONTEXT7_API_KEY: "os.environ/CONTEXT7_API_KEY"