---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
components:
  - ../../../../../components/alerts
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./cronjob.yaml
  - ./job.yaml
configMapGenerator:
  - name: zot
    files:
      - ./resources/config.json
  - name: ${APP}-volsync-values
    files:
      - values.yaml=volsync.values.yaml
generatorOptions:
  disableNameSuffixHash: true