---
apiVersion: batch/v1
kind: Job
metadata:
  name: zot-nuviostreams-build-initial
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--context=git://github.com/tapframe/NuvioStreamsAddon.git"
            - "--dockerfile=Dockerfile"
            - "--destination=zot.dev-system.svc.cluster.local:5000/nuviostreams:latest"
            - "--insecure"
            - "--insecure-pull"
      restartPolicy: OnFailure
