---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ps4-fpkgi
spec:
  targetNamespace: home-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  path: ./kubernetes/apps/home/media/ps4-fpkgi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  interval: 30m
