---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/tcproute_v1alpha2.json
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: forgejo-ssh
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ssh.forgejo.${DOMAIN1}
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: ssh
  rules:
    - backendRefs:
        - name: forgejo
          port: 2222
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: forgejo-ssh-dns
spec:
  endpoints:
  - dnsName: ssh.forgejo.${DOMAIN1}
    recordType: A
    targets:
    - 10.0.0.81  # Your Envoy VIP
    providerSpecific:
    - name: cloudflare-proxied
      value: "false" # <--- CRITICAL: Must be false for SSH