---
apiVersion: home.arpa/v1alpha1
kind: AppDatabase
metadata:
  name: vaultwarden
  namespace: home
spec:
  databaseName: vaultwarden
  groupRole: vaultwarden_grp
  schemaCreate: false
  createDb: true
