apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: game-fetcher-db-creds
  namespace: prod-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: game-fetcher-db-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DATABASE_URL: "postgres://{{ .username }}:{{ .password }}@pg-default-rw.db.svc.cluster.local:5432/gamefetcher?sslmode=disable"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/game-fetcher-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/game-fetcher-static
        property: password
