---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app game-fetcher
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  install:
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    disableWait: true
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      game-fetcher:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            vault.security.banzaicloud.io/vault-env-daemon: "true"
        containers:
          app:
            image:
              repository: zot.${DOMAIN1}/game-fetcher
              tag: 3dbaf24a7ac3dfe7a7b5b8337cdf67bcce501aa3
            env:
              PORT: &port "3000"
              RAWG: "vault:secret/data/ext_services#RAWG"
              OIDC_CLIENT_ID: "vault:secret/data/ext_services#OIDC_CLIENT_ID"
              OIDC_CLIENT_SECRET: "vault:secret/data/ext_services#OIDC_CLIENT_SECRET"
              BASE_URL: "https://game-fetcher.${DOMAIN1}"
              SOURCES: '[{"name":"FitGirl Local","url":"file://sources/fitgirl.json"}, {"name":"Dodi Local","url":"file://sources/dodi.json"}, {"name":"Kazumi Local","url":"file://sources/kazumi.json"}, {"name":"Xatab Local","url":"file://sources/xatab.json"}]'
              INDEX_INTERVAL: "1h"
              OIDC_ISSUER: "https://zitadel.${DOMAIN1}"
              OIDC_REDIRECT_URL: "https://game-fetcher.${DOMAIN1}/auth/callback"
              OIDC_SESSION_KEY: "super-secret-session-key-change-me"
              DATABASE_URL: "postgres://$${vault:database/creds/game-fetcher-role#username}:$${vault:database/creds/game-fetcher-role#password}@pg-default-rw.db.svc.cluster.local:5432/gamefetcher?sslmode=disable"
              TEMPORAL_HOST: "temporal.dev-system.svc.cluster.local:7233"
              TEMPORAL_NAMESPACE: "default"
              TEMPORAL_TASK_QUEUE: "game-fetcher"
              QBITTORRENT_URL: "http://qbittorrent.home-system.svc.cluster.local:8080"
              QBITTORRENT_USERNAME: "admin"
              QBITTORRENT_PASSWORD: "adminadmin"
              JDOWNLOADER_URL: "http://jdownloader.home-system.svc.cluster.local:3128"
              MEILISEARCH_URL: "http://meilisearch.db.svc.cluster.local:7700"
              MEILISEARCH_API_KEY: "super-secret-master-key"
              
              AUTH_SERVER_ADDR: auth-server.prod-system:50051
              SETTINGS_SERVER_ADDR: settings-server.prod-system:50051

              PROWLARR_URL:  http://prowlarr.home-system.svc.cluster.local:9696
              PROWLARR_API_KEY: "vault:secret/data/prowlarr#API_KEY"


              DOWNLOAD_GAME_FOLDER: games
              DOWNLOAD_MOVIE_FOLDER: movies

              SCAN_GAME_PATH: /games
              SCAN_MOVIE_PATH: /movies

              KETO_READ_URL: http://keto-read.keto.svc.cluster.local:80
              KETO_WRITE_URL: http://keto-write.keto.svc.cluster.local:80
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 16Mi
              limits:
                memory: 300Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: game-fetcher
        ports:
          http:
            port: *port
            appProtocol: kubernetes.io/ws
    serviceMonitor:
      app:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
        serviceName: *app
    route:
      app:
        hostnames:
          - "game-fetcher.${DOMAIN1}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /v1/traces
            backendRefs:
              - name: otel-collector
                namespace: observability
                port: 4318
          - matches:
              - path:
                  type: PathPrefix
                  value: /auth
              - path:
                  type: PathPrefix
                  value: /api/auth
            backendRefs:
              - name: auth-server
                namespace: prod-system
                port: 3000
          - backendRefs:
              - port: *port
                name: *app
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      media:
        existingClaim: copyparty-hdd
        globalMounts:
          - path: /games
            subPath: downloads/games
          - path: /movies
            subPath: downloads/movies
