---
apiVersion: v1
kind: Secret
metadata:
  name: aiostreams-secret
type: Opaque
stringData:
  SECRET_KEY: "abaa6ae0914135342793e335bec9ab22494c52c5aeb4850f6ed015e11947fe16"
  # Optional: Operator auth credentials (e.g. admin:password)
  AIOSTREAMS_AUTH: ""
