volumes:
  - name: home-assistant
    capacity: 5Gi
    restore:
      repository: offsite # or local
      previous: 7
  # - name: home-assistant-cache
  #   capacity: 1Gi
  #   offsite:
  #     enabled: false
