---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
components:
  - ../../../../../components/alerts
kind: Kustomization
resources:
  - repo.yaml
  - hr.yaml
  - netpol.yaml
