---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: debian-install-media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${STORE1}
  resources:
    requests:
      storage: 8Gi
