---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: debian-systemdisk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linstor-ssd
  resources:
    requests:
      storage: 30Gi
