apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    age.agekey: ENC[AES256_GCM,data:VVxVpsIMu0QPT0TTp0fgaegn04Vr6D07K3GGOkhFvH/ug012/Fr6+U9a1uapK8U9hZiGyExUqxKGN38eoZwD/h0w0+onKP1/XMk=,iv:7AaGDZlY4s0O8h6c/Lziqe3oVtfpqm6hHFdNlo0gU38=,tag:wDSQC0rYTs/b/6jdUQjg1Q==,type:str]
sops:
    age:
        - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOWV1Zkk3V3JzenozdUIr
            NjBmQVJxV0FFZlQ1VFdtTkdac21qZFZiZWhnCk9DQkJDUEJlMERkUTZSMkRhNUsr
            RFNSZUpRd3gvR0V1N3A3T1VmWnV3QTgKLS0tIHRRN01lNEJLWlFFUStBQ2xuZlc1
            VStkcXR6bFlGVmhxN2VJdHhkZEEycmMK16KA7M7V12ggawKjYdHO3msiZo/BFSM3
            Q2ta4wshHQtjcYbIFdt1l9OQXEQSgNF+CVbFub6orO4vXvlAC0h4xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T05:43:07Z"
    mac: ENC[AES256_GCM,data:yjWMXe0jLMVxAPlVDkpsSBTwe+ghP97dHrxqxVQKkfHg2vAAXJDZAGsByo3vrOsGqGzida9WFgf/UlwfvRFy27dPudrOkwgZkmHma1yQeQawOKB9AH5LG9yWjvgX5aH+ZoZZAdglGmG0xwZntLPQRg6iGVzK7EroGMJAK3ld9zU=,iv:pkULeSyfCC+qrBDheQdKWs3F5q/dbsFXAfKSG9IooKk=,tag:mEecnQ3GFtjdToq3KtpIlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
