apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: litellm-db-creds
  namespace: dev-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: litellm-db-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@pg-default-rw.db.svc.cluster.local:5432/litellm"
  data:
    - secretKey: username
      remoteRef:
        key: database/static-creds/litellm-static
        property: username
    - secretKey: password
      remoteRef:
        key: database/static-creds/litellm-static
        property: password
