---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kubevirt.io/virtualmachine_v1.json
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: windows-xp
  labels:
    app.kubernetes.io/name: windows-xp
spec:
  running: false
  template:
    metadata:
      annotations:
        kubevirt.io/disablePCIHole64: "true"
      labels:
        kubevirt.io/domain: windows-xp
        kubevirt.io/vm: windows-xp
    spec:
      terminationGracePeriodSeconds: 0
      domain:
        cpu:
          cores: 4
        devices:
          autoattachMemBalloon: false
          disks:
            # - name: install-media
            #   bootOrder: 1
            #   cdrom:
            #     bus: scsi
            - name: systemdisk
              bootOrder: 1
              disk:
                bus: scsi
          interfaces:
            - name: default
              masquerade: {}
              model: e1000
          inputs:
            - type: tablet
              bus: usb
              name: tablet1
        features:
          acpi: {}
          apic: {}
        # firmware:
        #   bootloader:
        #     bios: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 2048Mi
      networks:
        - name: default
          pod: {}
      volumes:
        # - name: install-media
        #   persistentVolumeClaim:
        #     claimName: windows-xp-install-media
        - name: systemdisk
          persistentVolumeClaim:
            claimName: windows-xp-systemdisk
